name: Push to itch.io

on:
  push:
    branches:
      - pipeline/*
    tags:
      - v*.*.*

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Zip
        run: |
          zip -qq -r ./source.zip ./*
      - name: Push to Itch
        uses: josephbmanley/butler-publish-itchio-action@v1.0.1
        env:
          CHANNEL: experiments-bundle
          ITCH_GAME: experiments
          ITCH_USER: pigdev
          PACKAGE: source.zip
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          VERSION_FILE: VERSION.txt
