name: Push to itch.io

on:
  push:
    branches:
      - pipeline/*
    tags:
      - v*.*.*

jobs:
  godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: []
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure
        env:
          PLATFORM: ${{ matrix.platform }}
          GITHUB_REF: ${{ github.head_ref }}
        run: |
          if [ "$PLATFORM" = "win32" ] || [ "$PLATFORM" = "win64" ]; then
            echo "::set-env name=EXPORT_SUFFIX::.exe"
          fi
          echo ${GITHUB_REF##*/} > VERSION.txt
          echo "Trigger build!"
      - name: Build Godot Project
        uses: josephbmanley/build-godot-action@v1.4.0
        id: godot_build
        with:
          name: pigdev-experiments
          preset: ${{ matrix.platform }}
          package: true
      - name: Push to Itch
        uses: josephbmanley/butler-publish-itchio-action@v1.0.1
        env:
          CHANNEL: experiments-bundle
          ITCH_GAME: experiments
          ITCH_USER: pigdev
          PACKAGE: ${{ github.workspace }}/${{ steps.godot_build.outputs.build }}
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          VERSION_FILE: VERSION.txt
